// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"Go-000/Week04/internal/biz"
	"Go-000/Week04/internal/data"
	"Go-000/Week04/internal/service"
	"github.com/go-redis/redis"
	"github.com/jinzhu/gorm"
)

// Injectors from wire.go:

func InitializeHello(db *gorm.DB, cache *redis.Client) *service.HelloService {
	helloRepository := data.NewHelloRepository(db, cache)
	helloBIZ := biz.NewHelloBIZ(helloRepository)
	helloService := service.NewHelloService(helloBIZ)
	return helloService
}
